[workspace]
resolver = "3"
members = ["crates/io"]

[workspace.package]
version = "0.0.1-alpha.1"
edition = "2024"
rust-version = "1.99"
license = "AGPL-3.0-only"
authors = ["NDDev OpenNetwork"]
homepage = "https://nddev.ai"
repository = "https://github.com/NDDev-OpenNetwork/nddev-device-sync-agent"
